# Generated by Django 5.2.3 on 2025-06-24 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('api_id', models.CharField(help_text='ID of the expansion in the Pokémon TCG API', max_length=50, unique=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('total_cards', models.IntegerField(blank=True, null=True)),
                ('symbol_url', models.URLField(blank=True, max_length=500, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expansion',
                'verbose_name_plural': 'Expansions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_id', models.CharField(help_text='ID of the card in the Pokémon TCG API', max_length=50, unique=True)),
                ('rarity', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url_small', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url_large', models.URLField(blank=True, max_length=500, null=True)),
                ('hp', models.CharField(blank=True, max_length=10, null=True)),
                ('types', models.JSONField(blank=True, help_text="Energy types of the card (e.g., ['Grass', 'Fire'])", null=True)),
                ('abilities', models.JSONField(blank=True, help_text='Abilities of the card', null=True)),
                ('attacks', models.JSONField(blank=True, help_text='Attacks of the card', null=True)),
                ('weaknesses', models.JSONField(blank=True, help_text='Weaknesses of the card', null=True)),
                ('resistances', models.JSONField(blank=True, help_text='Resistances of the card', null=True)),
                ('retreat_cost', models.JSONField(blank=True, help_text='Retreat cost of the card', null=True)),
                ('converted_retreat_cost', models.IntegerField(blank=True, null=True)),
                ('number', models.CharField(blank=True, help_text="Card number within the expansion (e.g., '1/100')", max_length=20, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('flavor_text', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='collection_manager.expansion')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['name'],
            },
        ),
    ]
