# Generated by Django 5.2.3 on 2025-07-26 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of copies of this specific card version owned by the user.')),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian'), ('JP', 'Japanese'), ('KR', 'Korean'), ('PT', 'Portuguese'), ('CH', 'Chinese')], default='EN', help_text='Language of the card.', max_length=2)),
                ('is_holographic', models.BooleanField(default=False, help_text='Is this copy of the card holographic?')),
                ('condition', models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged'), ('VG', 'Very Good')], default='NM', help_text='Physical condition of the card.', max_length=3)),
                ('is_first_edition', models.BooleanField(default=False, help_text='Is this a first edition print of the card?')),
                ('is_signed', models.BooleanField(default=False, help_text='Is this card signed?')),
                ('grade', models.CharField(blank=True, help_text="Professional grading score (e.g., 'PSA 10', 'BGS 9.5').", max_length=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this specific card instance.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='collection_manager.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "User's Card",
                'verbose_name_plural': "User's Cards",
                'unique_together': {('user', 'card', 'language', 'is_holographic', 'is_first_edition', 'condition')},
            },
        ),
    ]
