# Generated by Django 5.2.3 on 2025-08-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0002_usercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Is this card a favorite?'),
        ),
    ]
